name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  packages: write
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      -   name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

      -   name: Install
          uses: ./.github/actions/install
          with:
            node-version: ${{ env.NODE_VERSION }}
            node-registry: ${{ env.NODE_REGISTRY }}

      -   name: Build
          uses: ./.github/actions/build

      -   name: Commit & Publish
          id: changesets
          uses: changesets/action@v1
          with:
            publish: npm run release
            commit: "chore(release): publish"
            title: "chore(release): publish"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
